language: java
jdk: openjdk8
sudo: false

git:
  depth: false

before_install: chmod +x gradlew
install: ./gradlew setupDecompWorkspace

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build

before_deploy: git fetch origin refs/notes/*:refs/notes/*

deploy:
  provider: script
  script:
    ./gradlew curseforge
  skip_cleanup: true # to upload artifacts created during the build
  on:
    branch: master